services:
  wa-gateway:
    build: .
    container_name: wa-gateway
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./auth:/app/auth
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
